- name: Prepare ISO file
  hosts: rh-demo07-idrac
  gather_facts: false
  become: true
  tasks:
    - delegate_to: localhost
      block:
        - name: Reset iDRAC
          dellemc.openmanage.idrac_reset:
            idrac_ip: "{{ ansible_host }}"
            idrac_user: "{{ ansible_user }}"
            idrac_password: "{{ ansible_password }}"
            validate_certs: "{{ idrac_validate_certs | default(false, true) }}"
            ca_path: "{{ idrac_ca_path | default(omit, true) }}"
          register: reset

        - name: Wait for reset if the controller was ready but non responding
          ansible.builtin.pause:
            minutes: 4

        - name: Wait until LC_status is "READY"
          dellemc.openmanage.idrac_lifecycle_controller_status_info:
            idrac_ip: "{{ ansible_host }}"
            idrac_user: "{{ ansible_user }}"
            idrac_password: "{{ ansible_password }}"
            validate_certs: "{{ idrac_validate_certs | default(false, true) }}"
            ca_path: "{{ idrac_ca_path | default(omit, true) }}"
          register: lc_status
          until: lc_status.lc_status_info is defined and lc_status.lc_status_info.LCReady == true
          retries: 100
          delay: 20

        - name: Change BIOS password
          dellemc.openmanage.idrac_bios:
            idrac_ip: "{{ ansible_host }}"
            idrac_user: "{{ ansible_user }}"
            idrac_password: "{{ ansible_password }}"
            validate_certs: false
            attributes:
              SetupPassword: "delldell"
