---
- name: Integrating Dell Powerflex Storage with Openshift Container Platform - Remove SqlServer
  hosts: baremetal_hosts
  gather_facts: false

  tasks:
    - name: Delegate OCP login operations to localhost
      delegate_to: localhost
      block:
        - name: Set relevant facts for OCP Cluster
          ansible.builtin.set_fact:
            ocp_api_url: https://api.{{ ocp_cluster_name }}.{{ ocp_cluster_domain }}:6443

        - name: Login into OpenShift Container Platform cluster
          redhat.openshift.openshift_auth:
            host: "{{ ocp_api_url }}"
            username: "{{ lookup('env', 'K8S_AUTH_USERNAME') }}"
            password: "{{ lookup('env', 'K8S_AUTH_PASSWORD') }}"
            validate_certs: false
          register: openshift_auth_results

        - name: Retrieving OCP api_key
          ansible.builtin.set_fact:
            ocp_sno_api_key: "{{ openshift_auth_results.openshift_auth.api_key }}"

    - name: Delegate OCP operations to localhost
      delegate_to: localhost
      module_defaults:
        redhat.openshift.k8s:
          host: "{{ ocp_api_url }}"
          api_key: "{{ ocp_sno_api_key }}"
          validate_certs: false
          state: absent
          wait: true
      block:
        - name: Remove service for sqlserver
          redhat.openshift.k8s:
            definition: "{{ lookup('ansible.builtin.template', item) | from_yaml }}"
          loop:
            - manifests/sqlserver/sqlserver-service.yml.j2

        - name: Remove sqlserver on OCP
          redhat.openshift.k8s:
            definition: "{{ lookup('ansible.builtin.template', item) | from_yaml }}"
          loop:
            - manifests/sqlserver/sqlserver-deployment.yml.j2

        - name: Create PVC for sqlserver on OCP
          redhat.openshift.k8s:
            definition: "{{ lookup('ansible.builtin.template', item) | from_yaml }}"
          loop:
            - manifests/sqlserver/sqlserver-pvc.yml.j2

        - name: Remove anyuid scc to SA
          ansible.builtin.shell: oc --server "{{ ocp_api_url }}" --token={{ ocp_sno_api_key }} --insecure-skip-tls-verify adm policy remove-scc-from-user privileged system:serviceaccount:sqlserver:sqlserver-sa

        - name: Remove SA for sqlserver
          redhat.openshift.k8s:
            definition: "{{ lookup('ansible.builtin.template', item) | from_yaml }}"
          loop:
            - manifests/sqlserver/sqlserver-sa.yml.j2

        - name: Remove Job for sqlserver operations
          redhat.openshift.k8s:
            definition: "{{ lookup('ansible.builtin.template', item) | from_yaml }}"
          loop:
            - manifests/sqlserver/sqlserver-job.yml.j2

        - name: Remove SQLPad Deployment
          redhat.openshift.k8s:
            definition: "{{ lookup('ansible.builtin.template', item) | from_yaml }}"
          loop:
            - manifests/sqlserver/sqlpad-deployment.yml.j2

        - name: Remove SQLPad Service
          redhat.openshift.k8s:
            definition: "{{ lookup('ansible.builtin.template', item) | from_yaml }}"
          loop:
            - manifests/sqlserver/sqlpad-service.yml.j2

        - name: Remove SQLPad Route
          redhat.openshift.k8s:
            definition: "{{ lookup('ansible.builtin.template', item) | from_yaml }}"
          loop:
            - manifests/sqlserver/sqlpad-route.yml.j2

        - name: Remove namespace for the sqlserver workload
          redhat.openshift.k8s:
            definition: "{{ lookup('ansible.builtin.template', item) | from_yaml }}"
          loop:
            - manifests/sqlserver/sqlserver-namespace.yml.j2
