---
- name: Integrating Dell Powerflex Storage with Openshift Container Platform
  hosts: baremetal_hosts
  gather_facts: false
  tasks:
    - name: Delegate OCP login operations to localhost
      delegate_to: localhost
      block:
        - name: Set relevant facts for OCP Cluster
          ansible.builtin.set_fact:
            ocp_api_url: https://api.{{ ocp_cluster_name }}.{{ ocp_cluster_domain }}:6443

        - name: Login into OpenShift Container Platform cluster
          redhat.openshift.openshift_auth:
            host: "{{ ocp_api_url }}"
            username: "{{ lookup('env', 'K8S_AUTH_USERNAME') }}"
            password: "{{ lookup('env', 'K8S_AUTH_PASSWORD') }}"
            validate_certs: false
          register: openshift_auth_results

        - name: Retrieving OCP api_key
          ansible.builtin.set_fact:
            ocp_sno_api_key: "{{ openshift_auth_results.openshift_auth.api_key }}"

    - name: Delegate OCP operations to localhost
      delegate_to: localhost
      module_defaults:
        redhat.openshift.k8s:
          host: "{{ ocp_api_url }}"
          api_key: "{{ ocp_sno_api_key }}"
          validate_certs: false
          namespace: "{{ powerflex_namespace | default('powerflex', true) }}"
      block:
        - name: Creating OCP Resources to connect to Powerflex Storage - Namespace
          redhat.openshift.k8s:
            state: present
            definition: "{{ lookup('ansible.builtin.template', item) | from_yaml }}"
          loop:
            - powerflex/vxflexos-00-namespace.yml.j2

        - name: Creating OCP Resources to connect to Powerflex Storage - ConfigMap
          redhat.openshift.k8s:
            state: present
            definition: "{{ lookup('ansible.builtin.template', item) | from_yaml }}"
          loop:
            - powerflex/vxflexos-00-log-cm.yml.j2

        - name: Creating OCP Resources to connect to Powerflex Storage - ConfigMap
          redhat.openshift.k8s:
            state: present
            definition: "{{ lookup('ansible.builtin.template', item) | from_yaml }}"
          loop:
            - powerflex/vxflexos-00-config-cm.yml.j2

        - name: Creating OCP Resources to connect to Powerflex Storage - Auth Secret
          redhat.openshift.k8s:
            state: present
            definition: "{{ lookup('ansible.builtin.template', item) | from_yaml }}"
          loop:
            - powerflex/vxflexos-01-auth-secret.yml.j2

        - name: Creating OCP Resources to connect to Powerflex Storage - Config Secret
          redhat.openshift.k8s:
            state: present
            definition: "{{ lookup('ansible.builtin.template', item) | from_yaml }}"
          loop:
            - powerflex/vxflexos-02-config-secret.yml.j2

        - name: Creating OCP Resources to connect to Powerflex Storage - Operator Group
          redhat.openshift.k8s:
            state: present
            definition: "{{ lookup('ansible.builtin.template', item) | from_yaml }}"
          loop:
            - powerflex/vxflexos-03-operator-group.yml.j2

        - name: Create OCP Resources to connect to Powerflex Storage - Operator Subscription
          redhat.openshift.k8s:
            state: present
            definition: "{{ lookup('ansible.builtin.template', item) | from_yaml }}"
          loop:
            - powerflex/vxflexos-04-operator-subscription-object.yml.j2

        - name: Check Operator instantiation
          kubernetes.core.k8s_info:
            kind: Pod
            namespace: powerflex
            wait: true
            wait_sleep: 20
            label_selectors:
              - control-plane=controller-manager
          register: driver_status

        - name: Create OCP Resources to connect to Powerflex Storage - Operator Driver
          redhat.openshift.k8s:
            state: present
            definition: "{{ lookup('ansible.builtin.template', item) | from_yaml }}"
          loop:
            - powerflex/vxflexos-05-instantiate-operator-driver.yml.j2

        - name: Create OCP Resources to connect to Powerflex Storage - Storage Class
          redhat.openshift.k8s:
            state: present
            definition: "{{ lookup('ansible.builtin.template', item) | from_yaml }}"
          loop:
            - powerflex/vxflexos-06-storage-class.yml.j2
