---
- name: Remove volumes on ESXi
  hosts: esxi
  gather_facts: false
  tasks:
    - name: Remove VMFS datastores from vCenter
      community.vmware.vmware_host_datastore:
        hostname: '{{ vcenter_hostname }}'
        username: '{{ vcenter_username }}'
        password: '{{ vcenter_password }}'
        esxi_hostname: '{{ inventory_hostname }}'
        validate_certs: false
        datastore_name: "{{ item.vol_name }}"
        state: absent
      delegate_to: localhost
      loop: "{{ volumes_esxi }}"
      run_once: true

- name: Remove volume on Powerflex
  hosts: esxi
  serial: 1
  run_once: true
  gather_facts: false
  tasks:

  # There will be VMFS removal once it's done before powerflex volume removal ?
    - name: Create the SDC list for the volume removal
      ansible.builtin.set_fact:
        sdc_list: "{{ sdc_list | default([]) + [ {'sdc_name' : hostvars[item].sdc_hostname}] }}"
      loop: "{{ groups['esxi'] }}"

    - name: Unmap volume
      dellemc.powerflex.volume:
        gateway_host: "{{ FLEX_MGMT_IP }}"
        username: "{{ FLEX_MGMT_USER }}"
        password: "{{ FLEX_MGMT_PASS }}"
        verifycert: false
        vol_name: "{{ item.vol_name }}"
        size: "{{ item.vol_size }}"
        vol_type: "THIN_PROVISIONED"
        storage_pool_name: "{{ item.vol_pool }}"
        protection_domain_name: "{{ item.vol_pd }}"
        sdc: "{{ sdc_list }}"
        sdc_state: "unmapped"
        state: "present"
        allow_multiple_mappings: true
      delegate_to: localhost
      loop: "{{ volumes_esxi }}"

    - name: Delete volume
      dellemc.powerflex.volume:
        gateway_host: "{{ FLEX_MGMT_IP }}"
        username: "{{ FLEX_MGMT_USER }}"
        password: "{{ FLEX_MGMT_PASS }}"
        verifycert: false
        vol_name: "{{ item.vol_name }}"
        size: "{{ item.vol_size }}"
        vol_type: "THIN_PROVISIONED"
        storage_pool_name: "{{ item.vol_pool }}"
        protection_domain_name: "{{ item.vol_pd }}"
        state: "absent"
      delegate_to: localhost
      loop: "{{ volumes_esxi }}"
