---
- name: Setup SDC on host
  hosts: rh-demo10-os
  tasks:
    - name: Push sdc RPM
      ansible.builtin.copy:
        src: EMC-ScaleIO-sdc-3.6-400.107.el8.x86_64.rpm
        dest: /root/SDC.rpm
        mode: 0755

    - name: Install SDC RPM
      ansible.builtin.yum:
        name: /root/SDC.rpm
        state: present
        disable_gpg_check: true
      environment:
        MDM_IP: "{{ MDM_IP }}"

    - name: Set Fact with poweflex IP
      set_fact: 
        ipv4_powerflex: "{{ ansible_all_ipv4_addresses | ansible.utils.ipaddr(powerflex_subnet) }}"
    
    - name: check SDC list
      dellemc.powerflex.sdc:
        gateway_host: "{{ FLEX_MGMT_IP }}"
        username: "{{ FLEX_MGMT_USER }}"
        password: "{{ FLEX_MGMT_PASS }}"
        verifycert: false
        sdc_ip: "{{ ipv4_powerflex[0]}} "
        state: "present"
      delegate_to: localhost
      register: sdc_output

    - name: Rename SDC to rh-demo10 if not already done
      dellemc.powerflex.sdc:
        gateway_host: "{{ FLEX_MGMT_IP }}"
        username: "{{ FLEX_MGMT_USER }}"
        password: "{{ FLEX_MGMT_PASS }}"
        verifycert: false
        sdc_ip: "{{ipv4_powerflex[0]}}"
        sdc_new_name: "{{ sdc_hostname }}"
        state: "present"
      delegate_to: localhost
      when: sdc_output.sdc_details.name != sdc_hostname

    - name: Create and map a volume
      dellemc.powerflex.volume:
        gateway_host: "{{ FLEX_MGMT_IP }}"
        username: "{{ FLEX_MGMT_USER }}"
        password: "{{ FLEX_MGMT_PASS }}"
        verifycert: false
        vol_name: "{{ vol_name }}"
        size: "{{ vol_size }}"
        vol_type: "THIN_PROVISIONED"
        storage_pool_name: "{{ vol_pool }}"
        protection_domain_name: "{{ vol_pd }}"
        sdc:
          - sdc_name: "{{ sdc_hostname }}"
            access_mode: "READ_WRITE"
        sdc_state: "mapped"
        state: "present"
      delegate_to: localhost
