---
- name: Remove SDC from host
  hosts: rh-demo10-os
  tasks:
    - name: Remove SDC RPM
      ansible.builtin.yum:
        name: EMC-ScaleIO-sdc
        state: absent
        disable_gpg_check: true
      environment:
        MDM_IP: "{{ MDM_IP }}"

    - name: Unmap volume
      dellemc.powerflex.volume:
        gateway_host: "{{ FLEX_MGMT_IP }}"
        username: "{{ FLEX_MGMT_USER }}"
        password: "{{ FLEX_MGMT_PASS }}"
        verifycert: false
        vol_name: "{{ vol_name }}"
        size: "{{ vol_size }}"
        vol_type: "THIN_PROVISIONED"
        storage_pool_name: "{{ vol_pool }}"
        protection_domain_name: "{{ vol_pd }}"
        sdc:
          - sdc_name: "{{ sdc_hostname }}"
            access_mode: "READ_WRITE"
        sdc_state: "unmapped"
        state: "present"
      delegate_to: localhost

    - name: Delete volume
      dellemc.powerflex.volume:
        gateway_host: "{{ FLEX_MGMT_IP }}"
        username: "{{ FLEX_MGMT_USER }}"
        password: "{{ FLEX_MGMT_PASS }}"
        verifycert: false
        vol_name: "{{ vol_name }}"
        size: "{{ vol_size }}"
        vol_type: "THIN_PROVISIONED"
        storage_pool_name: "{{ vol_pool }}"
        protection_domain_name: "{{ vol_pd }}"
        state: "absent"
      delegate_to: localhost

    - name: Cleanup SDC entry
      delegate_to: localhost
      block:
        - name: Unmap volume
          dellemc.powerflex.volume:
            gateway_host: "{{ FLEX_MGMT_IP }}"
            username: "{{ FLEX_MGMT_USER }}"
            password: "{{ FLEX_MGMT_PASS }}"
            verifycert: false
            vol_name: "{{ vol_name }}"
            size: "{{ vol_size }}"
            vol_type: "THIN_PROVISIONED"
            storage_pool_name: "{{ vol_pool }}"
            protection_domain_name: "{{ vol_pd }}"
            sdc:
              - sdc_name: "{{ sdc_hostname }}"
                access_mode: "READ_WRITE"
            sdc_state: "unmapped"
            state: "present"

        - name: Delete volume
          dellemc.powerflex.volume:
            gateway_host: "{{ FLEX_MGMT_IP }}"
            username: "{{ FLEX_MGMT_USER }}"
            password: "{{ FLEX_MGMT_PASS }}"
            verifycert: false
            vol_name: "{{ vol_name }}"
            size: "{{ vol_size }}"
            vol_type: "THIN_PROVISIONED"
            storage_pool_name: "{{ vol_pool }}"
            protection_domain_name: "{{ vol_pd }}"
            state: "absent"

        - name: Get SDC id
          dellemc.powerflex.sdc:
            gateway_host: "{{ FLEX_MGMT_IP }}"
            username: "{{ FLEX_MGMT_USER }}"
            password: "{{ FLEX_MGMT_PASS }}"
            verifycert: false
            sdc_name: "{{ sdc_hostname }}"
            state: present
          register: sdc_output

        - name: Get token
          ansible.builtin.uri:
            url: "https://{{ FLEX_MGMT_IP }}/api/login"
            method: GET
            force_basic_auth: true
            user: "{{ FLEX_MGMT_USER }}"
            password: "{{ FLEX_MGMT_PASS }}"
            validate_certs: false
            return_content: true
          register: token

        - name: Remove SDC entry
          ansible.builtin.uri:
            url: "https://{{ FLEX_MGMT_IP }}/api/instances/Sdc::{{ sdc_output.sdc_details.id }}/action/removeSdc"
            method: POST
            force_basic_auth: true
            user: "{{ FLEX_MGMT_USER }}"
            password: "{{ token.json }}"
            headers:
              Content: "application/json"
            # Header to setup with token here.
            validate_certs: false
            return_content: true
