---
# Deploy a VM from a template using Ansible 'vmware_guest' module
- name: VM Operation on vCenter
  community.vmware.vmware_guest:
    hostname: '{{ deploy_vsphere_host }}'
    username: '{{ deploy_vsphere_user }}'
    password: '{{ deploy_vsphere_password }}'
    validate_certs: false
    datacenter: '{{ deploy_vsphere_datacenter }}'
    cluster: '{{ deploy_target }}'
    # esxi_hostname: '{{ deploy_target }}'
    folder: '{{ deploy_vsphere_folder }}'
    name: '{{ guest_hostname }}'
    # annotation: "{{ guest_notes }}"
    disk:
      - size_gb: '{{ guest_disksize }}'
        type: thin
    datastore: '{{ deploy_vsphere_datastore }}'
    networks: '{{ guest_networks }}'
    hardware:
      memory_mb: '{{ guest_memory }}'
      num_cpus: '{{ guest_vcpu }}'
    customization:
      domain: '{{ guest_domain_name }}'
      hostname: '{{ guest_hostname }}'
      dns_servers: '{{ guest_dns_servers }}'
      dns_suffix:
        - '{{ guest_domain_name }}'
    template: '{{ guest_template }}'
    wait_for_ip_address: true
    wait_for_ip_address_timeout: 180
    state: "{{ wanted_state | default('poweredon', true) }}"
    force: "{{ force | default(true, true) }}"
  delegate_to: localhost
